# ==============================================================================
# Home Assistant Main Configuration - Restructured
# File: configuration.yaml
# Updated: 2025-10-21
# Note: Consolidated to a single 'homeassistant' block to fix package loading.
# ==============================================================================

# ==============================================================================
# Core Home Assistant Configuration
# All 'homeassistant' settings are now in this single block.
# ==============================================================================
homeassistant:
  # Basic instance information
  name: "Smart Home - Pierre van Ryneveld"
  latitude: -25.84051
  longitude: 28.24814
  elevation: 1519
  unit_system: metric
  time_zone: Africa/Johannesburg
  country: ZA
  currency: ZAR
  
  # Network configuration for your static IP setup
  internal_url: "http://192.168.1.30:8123"
  external_url: "http://192.168.1.30:8123"  # Update if you have external access
  
  # File system access
  allowlist_external_dirs:
    - "/config/sensor_reports"
    - "/config/scripts"
    - "/tmp"
    - "/config/entity_exports"
    
  # Packages configuration - This will now be loaded correctly.
  packages: !include_dir_named packages

# ==============================================================================
# Load frontend themes from the themes folder
# ==============================================================================
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# ==============================================================================
# Load Automations, Scripts, Scenes, etc.
# ==============================================================================
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
group: !include groups.yaml

# ==============================================================================
# HTTP Configuration - Secure and Optimized
# ==============================================================================
http:
  # Core security settings
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 127.0.0.1
    - ::1
  
  # CORS configuration for your static IP and local access
  cors_allowed_origins:
    - "https://192.168.1.30:8123"
    - "http://192.168.1.30:8123"
    - "http://localhost:8123"
    - "http://127.0.0.1:8123"
    - "https://my.home-assistant.io"
  
  # Security settings
  login_attempts_threshold: 5
  ip_ban_enabled: true
  use_x_frame_options: true
  
  # SSL profile for better security
  ssl_profile: modern

# ==============================================================================
# Command Line Sensor
# ==============================================================================
command_line:
  - sensor:
      name: Badlogin
      command: "grep -c 'Login attempt' /home/hass/.homeassistant/home-assistant.log"

# ==============================================================================
# Logger Configuration
# ==============================================================================
logger:
  default: critical
  logs:
    homeassistant.components.http: warning
    homeassistant.core: warning
    homeassistant.loader: error
    homeassistant.setup: warning
    homeassistant.config: warning
    homeassistant.components.mqtt: warning
    homeassistant.components.tuya: warning
    homeassistant.components.automation: warning
    homeassistant.components.script: warning
    custom_components.alexa_media: warning
    custom_components.localtuya: warning
    custom_components.powercalc: error
    custom_components.solcast_solar: warning
    custom_components.ha_visualiser: error
    custom_components.o365: warning
    custom_components.sonoff: warning
    custom_components.deye: info
    custom_components.sunsunk: info
    homeassistant.components.network: error
    homeassistant.components.websocket: error
    homeassistant.components.recorder: warning
    homeassistant.components.history: error
    homeassistant.components.influxdb: warning
    homeassistant.components.system_health: error
    homeassistant.components.updater: error
    homeassistant.components.homeassistant: warning
    homeassistant.components.telegram: warning
    homeassistant.components.notify: warning
    homeassistant.util.dt: error
    homeassistant.util.yaml: error
    homeassistant.helpers.entity: error
    homeassistant.helpers.entity_registry: error
    homeassistant.helpers.device_registry: error
    urllib3.connectionpool: error
    requests.packages.urllib3.connectionpool: error
    aiohttp.access: error
    custom_components.hacs: warning

# ==============================================================================
# Text to Speech
# ==============================================================================
tts:
  - platform: google_translate  
    service_name: google_say

# ==============================================================================
# Recorder Configuration
# ==============================================================================
recorder:
  purge_keep_days: 30
  auto_purge: true
  auto_repack: true
  commit_interval: 5
  include:
    domains:
      - climate
      - person
      - device_tracker
      - automation
      - script
      - light
      - switch
    entities:
      - sensor.deyeinvertermaster_summary_battery_soc
      - sensor.deyeinverterslave_summary_battery_soc
      - sensor.deyeinvertermaster_today_energy_bought
      - sensor.deyeinvertermaster_today_energy_sold
      - sensor.deyeinvertermaster_today_load_consumption
      - sensor.deyeinverterslave_today_energy_bought
      - sensor.deyeinverterslave_today_energy_sold
      - sensor.deyeinverterslave_today_load_consumption
      - sensor.deyeinvertermaster_ac_output_active_power_r_total
      - sensor.deyeinverterslave_ac_output_active_power_r_total
  exclude:
    domains:
      - updater
      - sun
    entities:
      - sensor.date_time
      - sensor.time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.uptime
      - sensor.time_utc
      - sensor.last_boot
      - sensor.processor_use
      - sensor.processor_temperature
      - sensor.memory_use_percent
      - sensor.swap_use_percent
      - sensor.load_1m
      - sensor.load_5m 
      - sensor.load_15m
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - automation.daily_sensor_report_09h00_final
      - automation.extract_sensors_daily
    entity_globs:
      - sensor.*_update_available
      - sensor.hacs_*
      - binary_sensor.hacs_*
      - sensor.openweathermap_*
      - sensor.weather_*
      - device_tracker.unknown_*
      - sensor.node_red_*
      - sensor.telegram_*

# ==============================================================================
# Shell Commands
# ==============================================================================
shell_command:
  git_commit: '/config/scripts/git_commit.sh'
  backup_config: >
    cp -r /config /backup/ha-config-$(date +%Y%m%d_%H%M%S)
  check_system_status: >
    echo "System check at $(date)" > /config/system_check.log
  extract_sensors: >
    python3 /config/scripts/extract_sensors.py
  restart_deye_integration: >
    curl -X POST -H "Authorization: Bearer !secret ha_long_lived_token" \
    -H "Content-Type: application/json" \
    http://192.168.1.30:8123/api/config/config_entries/reload
  restart_homeassistant: >
    curl -X POST -H "Authorization: Bearer !secret ha_long_lived_token" \
    -H "Content-Type: application/json" \
    http://192.168.1.30:8123/api/services/homeassistant/restart
  cleanup_logs: >
    find /config -name "home-assistant.log*" -mtime +7 -delete && 
    find /config -name "*.log" -size +10M -delete
  check_log_size: >
    du -sh /config/home-assistant.log 2>/dev/null | cut -f1 > /config/log_size.txt || echo "0" > /config/log_size.txt
  cleanup_sensor_reports: >
    find /config/sensor_reports -type f -name "sensors_*" -mtime +14 -delete &&
    echo "Sensor reports older than 14 days deleted"

# ==============================================================================
# Other Integrations
# ==============================================================================
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

mobile_app: