reset_last_performed:
  name: Reset Last Performed
  description: >
    Resets the 'last_performed' date for a maintenance task entity, and updates the 'next_due' date based on the interval.
  fields:
    entity_id:
      name: Entity ID
      description: The ID of the task entity to reset.
      required: true
      selector:
        entity:
          domain: binary_sensor
    performed_date:
      name: Performed Date
      description: Optionally specify the date the task was last performed.
      required: false
      example: "2025-06-01"
      selector:
        date: