# Home Assistant template sensor to summarize all core, supervisor, OS, and integration/add-on updates.
# Place this file in your 'sensors' directory (e.g., /config/sensors/update_summary.yaml).
# You must include this file in your configuration.yaml with: sensor: !include sensors/update_summary.yaml

- platform: template
  sensors:
    home_assistant_updates_summary:
      friendly_name: "Home Assistant Updates Summary"
      unique_id: home_assistant_updates_summary
      value_template: >
        {% set updates = [] %}
        {% if states('update.home_assistant_core_update') == 'on' %}
          {% set updates = updates + ['Home Assistant Core'] %}
        {% endif %}
        {% if states('update.home_assistant_supervisor_update') == 'on' %}
          {% set updates = updates + ['Home Assistant Supervisor'] %}
        {% endif %}
        {% if states('update.home_assistant_operating_system_update') == 'on' %}
          {% set updates = updates + ['Home Assistant OS'] %}
        {% endif %}
        {% for s in states.update if s.state == 'on' and not s.entity_id.startswith('update.home_assistant') %}
          {% set updates = updates + [s.name] %}
        {% endfor %}
        {{ updates | join(', ') if updates else 'No updates available' }}
      attribute_templates:
        updates_list: >
          {% set updates = namespace(list=[]) %}
          {% if states('update.home_assistant_core_update') == 'on' %}
            {% set updates.list = updates.list + ['Home Assistant Core'] %}
          {% endif %}
          {% if states('update.home_assistant_supervisor_update') == 'on' %}
            {% set updates.list = updates.list + ['Home Assistant Supervisor'] %}
          {% endif %}
          {% if states('update.home_assistant_operating_system_update') == 'on' %}
            {% set updates.list = updates.list + ['Home Assistant OS'] %}
          {% endif %}
          {% for s in states.update if s.state == 'on' and not s.entity_id.startswith('update.home_assistant') %}
            {% set updates.list = updates.list + [s.name] %}
          {% endfor %}
          {{ updates.list }}
        detailed_status: >
          {
            "Home Assistant Core": "{{ states('update.home_assistant_core_update') }}",
            "Supervisor": "{{ states('update.home_assistant_supervisor_update') }}",
            "OS": "{{ states('update.home_assistant_operating_system_update') }}",
            {% for s in states.update if not s.entity_id.startswith('update.home_assistant') %}
              "{{ s.name }}": "{{ s.state }}"{% if not loop.last %},{% endif %}
            {% endfor %}
          }