notify:
#===============================================================================
# Email Configuration
# Purpose: All email service settings
#===============================================================================
  # Email services (confirmed working)
  - name: email_ha
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: jbarkhuizen@gmail.com
    encryption: starttls
    username: jbarkhuizen@gmail.com
    password: !secret gmail_app_password
    recipient: jbarkhuizen@gmail.com
    sender_name: "Home Assistant General"
#-------------------------------------------------------------------------------
  - name: email_sensors
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: jbarkhuizen@gmail.com
    encryption: starttls
    username: jbarkhuizen@gmail.com
    password: !secret gmail_app_password
    recipient: jbarkhuizen@gmail.com
    sender_name: "HA Sensor Reports"
#-------------------------------------------------------------------------------
  - name: email_alerts
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: jbarkhuizen@gmail.com
    encryption: starttls
    username: jbarkhuizen@gmail.com
    password: !secret gmail_app_password
    recipient: jbarkhuizen@gmail.com
    sender_name: "HA Alert System"