#===============================================================================
# Frontend Optimization Package - Corrected
# File: packages/frontend_optimization.yaml
# Updated: 2025-09-12  
# Purpose: Frontend performance management (without invalid configurations)
#===============================================================================

# Frontend management automation
automation:
  # Frontend theme reload (weekly)
  - id: frontend_theme_reload
    alias: "Frontend Theme Reload - Weekly"
    description: "Reload themes weekly for consistency"
    trigger:
      - platform: time
        at: "03:00:00"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - service: frontend.reload_themes
        data: {}
      - delay:
          seconds: 30
      - service: telegram_bot.send_message
        data:
          config_entry_id: 01K7PH2MD1SA9VXHCP39WVCJM4
          target: !secret telegram_chat_id
          message: |
            🎨 Frontend themes reloaded
            
            Weekly theme reload completed for consistency.

# Scripts for frontend management
script:
  reload_frontend_themes:
    alias: "Reload Frontend Themes"
    sequence:
      - service: frontend.reload_themes
        data: {}
      - service: telegram_bot.send_message
        data:
          config_entry_id: 01K7PH2MD1SA9VXHCP39WVCJM4
          target: !secret telegram_chat_id
          message: "🎨 Frontend themes reloaded successfully"

  clear_browser_cache_instructions:
    alias: "Browser Cache Clearing Instructions"
    sequence:
      - service: persistent_notification.create
        data:
          title: "🧹 Clear Browser Cache"
          message: |
            To clear frontend cache and resolve display issues:
            
            **Chrome/Edge:**
            1. Press F12 (Developer Tools)
            2. Right-click refresh button  
            3. Select "Empty Cache and Hard Reload"
            
            **Firefox:**
            1. Press Ctrl+Shift+R (Hard refresh)
            
            **Mobile:**
            1. Clear browser data in settings
            2. Force-close and reopen browser
            
            This resolves most frontend display issues.

#===============================================================================