# packages/google_drive_config.yaml
# FIXED - Google Drive Backup Configuration for installed integration
# This file works when the Google Drive Backup integration is installed

# NOTE: The main google_drive_backup: configuration should NOT be in packages
# It should be configured through the integration UI (Settings → Integrations)
# This package file only contains sensors and automations that work WITH the integration

# Template sensors for monitoring Google Drive Backup
sensor:
  - platform: template
    sensors:
      google_drive_backup_status_enhanced:
        friendly_name: "Google Drive Backup Status Enhanced"
        value_template: >
          {% if states('sensor.backup_state') %}
            {{ states('sensor.backup_state') }}
          {% else %}
            Unknown
          {% endif %}
        icon_template: >
          {% if states('sensor.backup_state') == 'backed_up' %}
            mdi:cloud-check
          {% elif states('sensor.backup_state') == 'backing_up' %}
            mdi:cloud-upload
          {% else %}
            mdi:cloud-alert
          {% endif %}
      
      google_drive_last_backup_formatted:
        friendly_name: "Google Drive Last Backup Formatted"
        value_template: >
          {% if state_attr('sensor.backup_state', 'last_backup') %}
            {{ as_timestamp(state_attr('sensor.backup_state', 'last_backup')) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}
          {% else %}
            Never
          {% endif %}
        icon_template: mdi:calendar-clock
      
      google_drive_next_backup_formatted:
        friendly_name: "Google Drive Next Backup Formatted"
        value_template: >
          {% if state_attr('sensor.backup_state', 'next_backup') %}
            {{ as_timestamp(state_attr('sensor.backup_state', 'next_backup')) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}
          {% else %}
            Not Scheduled
          {% endif %}
        icon_template: mdi:calendar-plus
      
      google_drive_backup_size_gb:
        friendly_name: "Google Drive Backup Size GB"
        value_template: >
          {% if state_attr('sensor.backup_state', 'size_in_google_drive') %}
            {{ (state_attr('sensor.backup_state', 'size_in_google_drive') / 1024 / 1024 / 1024) | round(2) }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "GB"
        icon_template: mdi:harddisk

# Binary sensors for backup health monitoring
binary_sensor:
  - platform: template
    sensors:
      google_drive_backup_health_status:
        friendly_name: "Google Drive Backup Health Status"
        value_template: >
          {% if state_attr('sensor.backup_state', 'last_backup') %}
            {% set last_backup = state_attr('sensor.backup_state', 'last_backup') %}
            {% set hours_since = (as_timestamp(now()) - as_timestamp(last_backup)) / 3600 %}
            {{ hours_since < 26 }}
          {% else %}
            false
          {% endif %}
        device_class: connectivity
        icon_template: >
          {% if is_state('binary_sensor.google_drive_backup_health_status', 'on') %}
            mdi:cloud-check
          {% else %}
            mdi:cloud-alert
          {% endif %}
      
      google_drive_backup_critical_status:
        friendly_name: "Google Drive Backup Critical Status"
        value_template: >
          {% if state_attr('sensor.backup_state', 'last_backup') %}
            {% set last_backup = state_attr('sensor.backup_state', 'last_backup') %}
            {% set hours_since = (as_timestamp(now()) - as_timestamp(last_backup)) / 3600 %}
            {{ hours_since > 48 }}
          {% else %}
            true
          {% endif %}
        device_class: problem
        icon_template: >
          {% if is_state('binary_sensor.google_drive_backup_critical_status', 'on') %}
            mdi:alert-circle
          {% else %}
            mdi:check-circle
          {% endif %}