#===============================================================================
# Advanced System Logging Package
# File: packages/system_logging.yaml
# Updated: 2025-09-12
# Purpose: Log management and system monitoring
#===============================================================================

# Log management sensors
template:
  - sensor:
      # Log file size monitor
      - name: "Log File Size"
        unique_id: log_file_size
        unit_of_measurement: "MB"
        state: >
          {% set size = states('sensor.log_file_size_mb') | float(0) %}
          {{ (size / 1024 / 1024) | round(2) if size > 0 else 0 }}
        icon: mdi:file-document

  - binary_sensor:
      # Log file growth warning
      - name: "Log File Growth Warning"
        unique_id: log_file_growth_warning
        device_class: problem
        state: >
          {{ states('sensor.log_file_size') | float(0) > 50 }}

# Log management automations
automation:
  # Log file cleanup automation
  - id: log_file_cleanup
    alias: "Log File Cleanup - Weekly"
    description: "Clean up old log files weekly"
    trigger:
      - platform: time
        at: "09:30:00"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - service: shell_command.cleanup_logs
        data: {}
      - service: telegram_bot.send_message
        data:
          config_entry_id: 01K7PH2MD1SA9VXHCP39WVCJM4
          target: !secret telegram_chat_id
          message: |
            🧹 Log file cleanup completed
            
            Weekly log maintenance performed at {{ now().strftime('%H:%M:%S') }}
            System performance should be optimal.

# Log management scripts
script:
  check_log_size:
    alias: "Check Log File Size"
    sequence:
      - service: shell_command.check_log_size
        data: {}
      - delay:
          seconds: 5
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.log_file_size

  enable_debug_logging:
    alias: "Enable Debug Logging (Temporary)"
    sequence:
      - service: logger.set_level
        data:
          homeassistant.core: debug
          custom_components: debug
      - delay:
          hours: 1
      - service: logger.set_level
        data:
          homeassistant.core: warning
          custom_components: warning
      - service: telegram_bot.send_message
        data:
          config_entry_id: 01K7PH2MD1SA9VXHCP39WVCJM4
          target: !secret telegram_chat_id
          message: "🔍 Debug logging automatically disabled after 1 hour"

#===============================================================================